# -*- coding: utf-8 -*-

DB_CREATE = [
    '''
CREATE TABLE SONGS (
    PATH TEXT UNIQUE NOT NULL,
    SOURCE TEXT NOT NULL,
    EXTENSION TEXT NOT NULL,
    LENGTH INTEGER NOT NULL,
    PRIMARY KEY(PATH)
);
    ''',
    '''
CREATE TABLE SONGS_YOUTUBE (
    SONG TEXT,
    YOUTUBE_ID TEXT UNIQUE NOT NULL,
    PRIMARY KEY(SONG),
    FOREIGN KEY(SONG) REFERENCES SONGS(PATH) ON DELETE CASCADE
);
    ''',
    '''
CREATE TABLE PLAYLISTS (
    ID TEXT,
    SONGS TEXT,
    PRIMARY KEY (ID)
);
    '''
]

#
### SONGS
#

SONGS_CREATE = '''
INSERT INTO SONGS (PATH,SOURCE,EXTENSION,LENGTH)
VALUES (:path,:source,:extension,:length)
'''

SONGS_DELETE = '''
DELETE FROM SONGS;
'''

SONGS_READ = '''
SELECT * FROM SONGS;
'''


#
### SONGS_YOUTUBE
#
SONGS_YOUTUBE_CREATE = '''
INSERT INTO SONGS_YOUTUBE (SONG,YOUTUBE_ID)
VALUES (:path,:youtube_id)
'''

# SONGS_YOUTUBE_DELETE = '''
# DELETE FROM SONGS_YOUTUBE;
# '''

SONGS_YOUTUBE_READ_IDS = '''
SELECT YOUTUBE_ID FROM SONGS_YOUTUBE;
'''


#
### PLAYLISTS
#
PLAYLISTS_UPSERT = '''
INSERT or REPLACE INTO PLAYLISTS(ID,SONGS)
VALUES (:list_id,:songs_ids)
'''

PLAYLISTS_DELETE = '''
DELETE FROM PLAYLISTS
WHERE ID=:list_id
'''

PLAYLISTS_READ = '''
SELECT * FROM PLAYLISTS
'''
